config/routes.rb
Rails.application.routes.draw do
  resources :tools_categories do
    resources :tools
  end

  root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tool.rb
class Tool < ApplicationRecord
  require 'csv'
  belongs_to :tool_category

  extend FriendlyId
  friendly_id :name, use: :slugged

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Tool.create! row.to_hash
    end
  end
end

app/models/tool_category.rb
class ToolCategory < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tool_categories = ToolCategory.all
  end
end

app/controllers/tools_categories_controller.rb
class ToolsCategoriesController < ApplicationController

  def index
    @tool_category = ToolCategory.all
  end

  def show
    @tool_category = ToolCategory.friendly.find(params[:id])
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = Tool.all
  end

  def show
    @tool = Tool.friendly.find(params[:id])
  end

  def import 
    Tool.import(params[:file])
    redirect_to root_url, notice: "Tools imported!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tool_category_helper.rb
module ToolCategoryHelper
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/views/home/index.html.erb
<h2>Home page!</h2>


<div class="row">
  <% @tool_categories.each do |tool|%>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">

        <%= link_to "#{tool.name}", tools_category_path(tool) %>
        <p class="card-text">With supporting <%= tool.description %>.</p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyToolbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tools/index.html.erb
<h1>Check out all the options near you!</h1>

<div class="row">
<div class="col col-lg-6">
<% @tools.each do |tool| %> 
  <div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-6">
      <p><%= tool.name %></p>
      <p><%= tool.description %></p>
  
    </div>

  </div>
<% end %>
</div>
</div>

<div>
  <ul>
    <li>Name: <%= (Gems.info 'rails_admin')["name"] %></li>
    <li>Description: <%= (Gems.info 'rails_admin')["info"] %></li>
    <li>Score: <%= (Gems.info 'rails_admin')["downloads"] %></li>
    <li>Created at: <%= (Gems.versions 'rails_admin').last["created_at"] %> </li>
    <li>Updated at: <%= (Gems.versions 'rails_admin').first %></li>

  </ul>
  
  

</div>

app/views/tools/show.html.erb
<h2><%= @tool.name %></h2>

app/views/tools_categories/index.html.erb
<h1>Check out all the options that you have with Ruby!</h1>

<div class="row">
<div class="col col-lg-6">
<% @tool_category.each do |tool| %> 
  <div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-6">
      <p><%= tool.name %></p>
      <p><%= tool.description %></p>

    </div>

  </div>
<% end %>


app/views/tools_categories/show.html.erb
<h2><%= @tool_category.name %></h2>